### ISSUE TITLE
Samsung LC34G55T volume control is not working

### ISSUE THREAD

**Issue by Delitants** [the0neyouseek/MonitorControl#1042]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Samsung LC34G55T volume control is not working. Period.

### Expected behavior

So volume to change

### Anything else?

There is no DDC settings in the monitor menu

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.6
- Mac model: Intel
- MonitorControl version: 4.0.2
- Monitor(s): Samsung LC34G55T
- Monitor Cable(s)/Connection(s): HDMI
- Apple Silicon/M1 (yes or no): no
```

**Comment by the0neyouseek** [comment]
Hi @Neolo 
Just reading quickly it doesn't seems like the LC34G55T has integrated speakers ? Do you wish to control you mac internal speakers ?

**Comment by Neolo** [comment]
It has audio jack output for external speakers. Volume is controlled by monitor button only.

**Comment by jperkin** [comment]
I'm seeing the same with my Samsung LF32TU87, though in this case I'm connected over Thunderbolt.

The display controls work ok, though I have to use "Software (gamma, forced)", otherwise it only starts dimming the screen at around 60%.  However the audio controls do nothing, even though the icon shows up and is adjusting as expected, the output volume through the speakers remains unchanged.

**Comment by x-magic** [comment]
> The display controls work ok, though I have to use "Software (gamma, forced)", otherwise it only starts dimming the screen at around 60%. However the audio controls do nothing, even though the icon shows up and is adjusting as expected, the output volume through the speakers remains unchanged.

I'm using Dell U4320Q and have the same issue - if the display is connected via DP or USB-C alt mode directly, DDC works for both picture and sound. But if connected via a Thunderbolt dock, only software control works. DDC can still be detected however, just controls won't work anymore.

**Comment by txoof** [comment]
Similar issue using a Dell U2723QE over a display port connection. The monitor has no internal speakers.
Setup:

- M1 Mac Mini Monterey 12.5
- Display Port Connection to U2723QE
- Powered speakers connected via 2.5mm jack

Symptoms:

- Output volume does not follow adjustments made via keyboard or MonitorControl app.
- Display dimming works as expected
- Volume control overlay appears and works as expected, when using F10-F12
- Volume slider in menu bar appears and can be adjusted

**Comment by samu20108** [comment]
I have same issue with my Samsung S27HG5x when using usb c dock. If I use only usb c-hdmi adapter all works perfectly.

**Comment by waydabber** [comment]
Many displays do not properly support volume control over DDC. If brightness control works properly (not only the bottom 50% which indicates that DDC control is not working at all, either because of the use of the built-in HDMI port or lack of display support) and volume control does not, then there is nothing to do on the app side, but the display's firmware is at fault.
