### ISSUE TITLE
 Better way of lowering contrast after brightness 

### ISSUE THREAD

**Issue by MHX792** [the0neyouseek/MonitorControl#114]
Currently, when the lowest brightness setting is reached, it will lower the contrast. Unfortunately the lowering is too strong. It drops to a too way contrast level.

I made suggestions for how to improve this backed by code in this thread:
https://github.com/JoniVR/MonitorControl/issues/3

Hopefully, you will find some time to implement it. I use it with an old version since 8 months now and would not want to miss the convenience any more. Can recommend +100.

**Comment by JoniVR** [comment]
I think this is very much related to #31, so I'm going to close this issue and we'll consider it part of that issue. 

I don't think it would be a lot of work to implement since I basically already implemented it on a separate branch of my fork (https://github.com/JoniVR/MonitorControl/commit/59620bbba324d89629d5cea5116d1eee4f9aa578) before shifting focus to this repo.
