### ISSUE TITLE
Functions keys aren't working

### ISSUE THREAD

**Issue by nekrasovdmitriy** [the0neyouseek/MonitorControl#13]
Thank you for your work, app is super cool, best looking monitor brightness manager on macOS nowdays. Working fine with my Viewsonic and Dell. App starts at login, but f1-f2 keys still don't work for changing brightness. Or maybe there is another shortcut? 

**Some suggestions:** 
Ability of changing order of displays in preferences. (now second display is first, first display is second in menu bar).
If function keys will work, let them listen for contrast change too.

**Comment by Amir-Hass** [comment]
I use Karabiner-Elements to map my tilde key (next to #1) to the "fn" key on a first-party Apple keyboard, so I can use them. Works flawlessly.

**Comment by nekrasovdmitriy** [comment]
I use Apple keyboard with numpad, so i have fn key. But fn+f1 or f2 don`t work too.

**Comment by the0neyouseek** [comment]
Hi @nekrasovdmitriy & @Amir-Hass ,

First, thanks for the feedback 😄 always nice to hear someone enjoy this.

I'll look into the function keys bug tomorrow if I have time or next weekend. My current setup is an Mbp with one external keyboard (from Apple) and one external monitor (Asus PB279Q) so it's a little bit tricky for me to test all cases but I'll try.

For me (without Karabiner installed) both function keys and native keys are working (so with or without the <kbd>fn</kbd> key pushed down). If it isn't for you please check that you have enabled the app in macOS Accessibility settings. If it's still not working, well…, I'll try to find what causes this and fix it in the next version.

Have a nice day

**Comment by nekrasovdmitriy** [comment]
Maybe it works for because you native apple keyboard and display (built in your MBP) with native  brightness control with f1/f2. In my case, i have Mac Pro with third party displays and didn't have ability to control their brightness by keyboard from the start.

**Comment by falcn** [comment]
I have Macbook, but F1/F2 keys are not working for me as well. MonitorControl is enabled in Accessibility panel. I've tried enabling/disabling "Use F1, F2 etc as standard function keys", and tried to press keys both with and without Fn, no luck.

Although app definitely highjacks these keys, because, with app running, I'm unable to control internal display brightness while I have a focus in a window on the external monitor (which is an intended behavior AFAIK)

**Comment by the0neyouseek** [comment]
Okay guys,

I've uploaded a new version `v1.2.1` could you try it and see if it works better now, I'm still trying to figure out what's wrong with my code…

**Comment by falcn** [comment]
Still not working for me.

**Comment by falcn** [comment]
One thing I noticed: MonitorControl hijacks F1-F2 (they stop working in other apps), while it should use Fn-F1 and Fn-F2, because I have "use F1, F2 etc as standard function keys". I have an app SoundControl which replaces built-in volume control, it interprets hotkeys correctly: Fn-F11 is reduce volume, F11 is unaffected. I can link apps here on github that use brightness control hotkeys correctly, and use native hud as well if it would help.

**Comment by Amir-Hass** [comment]
I'm having that issue too even when I have Function keys set to be standard in kraberiner. With my third party keyboard I set the tilde key to be Fn for the control but it's not working as F1 and F2 adjust brightness without the tilde key pressed

**Comment by the0neyouseek** [comment]
Okay, I think see where the problem is. 

I use the standard keycodes for the function keys and capture the event directly from it. I did not test with karabiner but It may be what prevent your mapping from working, I'll look into that.

And, yes @falcn , MonitorControl hijacks those key because the lib I use is made to do that. It is the intended behavior as, for me, those key should only do that, but, you raise a good point being that it should work for you only if <kbd>fn</kbd> is pressed.

I'll correct that in the next version.

**Comment by nekrasovdmitriy** [comment]
Still not working for me. I have not Karabiner installed, app is allowed in security settings. Sliders controls works well for both displays but f1-f2 keys do nothing.

**Comment by the0neyouseek** [comment]
Hmm @nekrasovdmitriy,

Can you please tell me a bit more, what keyboard do you have ? Do you have the option "use F1, F2 etc as standard function keys" enabled ? What macOS version are you on ?

**Comment by nekrasovdmitriy** [comment]
Sure. I have wired Apple Magic Keyboard with numpad, macOS 10.13.3 on Mac Pro 5.1, option "use F1, F2 etc as standard function keys"  is disabled. (i tried to turn it on, it did not help)

**Comment by the0neyouseek** [comment]
Okay thats weird, I have the exact same setup right in front of me and it works... What's your setup like ? Mbp + external screen(s) ? iMac + external screen(s) ? other ?

**Comment by nekrasovdmitriy** [comment]
Mac Pro 5.1 + two external displays: Dell and ViewSonic. Pay attention, that my setup does not have native apple built-in display, as in iMac or Mbp, only third party party monitors. Maybe it can be a problem?

**Comment by the0neyouseek** [comment]
Okay, thanks @nekrasovdmitriy , I'll look into it asap.

**Comment by falcn** [comment]
@the0neyouseek  my point was: it hijacks keys (meaning that this part is working as intended), but input is ignored (regardless of the state of "use F1, F2 etc as standard function keys"). Just trying to help to pinpoint the issue.

**Comment by Amir-Hass** [comment]
I'm on 10.12.6 with a corsair K70 keyboard. Two external monitors From ASUS.

**Comment by foyzur** [comment]
This does not work for me as well. I have a Macbook pro 14,1 with a non Apple USB keyboard and a DELL U3415W. Tested with both Karabiner-elements enabled and disabled. The slider works pretty well.

**Comment by dzg** [comment]
First, @the0neyouseek, this is awesome, thanks!

Brightness keys aren't working for me either. I have an Apple large keyboard on a Hackintosh. Tried all kinds of combos of fn key, tried FunctionFlip, etc.

**Comment by reitermarkus** [comment]
The keys (neither with nor without <kbd>Fn</kbd>) are also not working for me on an Apple Magic Keyboard on a Hackintosh. It does however work with <kbd>Fn</kbd> if I use https://github.com/Bensge/NativeDisplayBrightness/releases/tag/v0.0.5, so maybe this could serve as a pointer towards the cause.

**Comment by nekrasovdmitriy** [comment]
I can also confirm that F1/F2 + Fn keys works for me in https://github.com/Bensge/NativeDisplayBrightness/releases/tag/v0.0.5

**Comment by falcn** [comment]
Function keys are working in https://github.com/the0neyouseek/MonitorControl/releases/tag/v1.1

**Comment by nekrasovdmitriy** [comment]
@falcn Not for me.

**Comment by bartekrutkowski** [comment]
I can confirm that 1.2.1 version doesn't work with Apple Keyboard (F1/F2 keys) for Dell U2718Q monitor, even though the volume keys (F10/F11/F12) are working and the brightness slider is working.

**Comment by reitermarkus** [comment]
For me with a Magic Keyboard, in 1.1, brightness using F1/F2 does not work, but volume using F11/F12 does.

**Comment by waydabber** [comment]
I can confirm the same issue. Tested on a Mac Mini 2012 (+ Lenovo L24Q) with Apple Wireless Keyboard and a Macbook 2017 (+ LG L27UD88) with an Apple Wireless Keyboard. Both running High Sierra 10.13.3 (17D102). Sliders are working fine. Neither the brightness (F1/F2) nor the volume (F11/F12) keys do nothing. The volume keys are properly hijacked by the app (since the standard F11/F12 volume keys are unresponsive when the app listens for "Both Brightness & Volume"), but the volume is not controlled and the volume level overlay is not shown.

**Comment by the0neyouseek** [comment]
Hi everyone,

Thanks for all your reports, I'll try to have a look quickly to fix this (annoying) bug ! (Hopefully by next week)

**Comment by reitermarkus** [comment]
I tried to look into this, and it seems that it's not storing the settings correctly by default. After I unchecked and checked my display in the “Display” tab, it started working. Weirdly, I cannot reproduce it by removing the `.plist`, so I'm not 100% sure that this is the problem.

**Comment by waydabber** [comment]
@reitermarkus - thanks for the tip, this solved the issue for me! :)

**Comment by nekrasovdmitriy** [comment]
@reitermarkus Yes, after this tip function keys start working at last, big thanks.

**Comment by the0neyouseek** [comment]
Thanks @reitermarkus for looking into this, I've got to say I didn't really had the opportunity to 👍

New version is available now right here [`v1.3.0`](../releases/tag/v1.3.0)
