### ISSUE TITLE
Feature: change brightness/volume for all displays, including internal

### ISSUE THREAD

**Issue by Amir-Hass** [the0neyouseek/MonitorControl#14]
The setting to change brightness and volume at the same time for all displays doesn't work. This happens both with the keyboard shortcut and the menu bar widget, they only do one display at a time. (version 1.2)

**Comment by the0neyouseek** [comment]
Hi again @Amir-Hass ,

Thank you for testing this, as I currently don't have a multi-monitor setup I couldn't test it well. I'll try to see if I can find another monitor to squash this bug soon.

Have a nice day !

**Comment by funbben** [comment]
I confirm it doesn't work, changing brightness/contrast with sliders works fine, for external monitor but doesn't work for internal display.

**Comment by the0neyouseek** [comment]
Hi @funbben ,

Actually, this was not what I had in mind with this option. MonitorControl doesn't handle at all the internal display, so the settings should only affect (in theory since I haven't tested it) external display for now.

But as it's a very good suggestion I'll had this to the list of things to do. (Maybe as a separate setting for example)

**Comment by marcelfarres** [comment]
I would love to be able to control internal+external brightness together.

**Comment by cseelus** [comment]
@the0neyouseek Maybe you could use code from [Brightness Menulet](https://github.com/florianbeck/BrightnessMenulet) to achieve this.

Brightness Menulet sets the brightness for the internal screen as well. 

One thing thats really convenient, is the option to follow the main screens (internal screens) brightness, which dims/brightens the external display automatically with the internal display, when the ambient light sensor of the iMac/MacBook detects changes there.

**Comment by retrography** [comment]
@cseelus: Your excellent idea is being explored here: #27.

**Comment by retrography** [comment]
The idea of controlling the internal monitor along with the external is great. It has some caveats, though:

1. The grading of the brightness control is not always the same between internal and external. My understanding is that my external monitor as a more linear grading while the internal MacBook monitor seems to follow a more "visual" logic. 
2. The minimums are not the same.The internal monitor literally turns the backlight off when the brightness hits 0. The external, never.
3. The maximums are not the same. My internal monitor (on 2016 Pro) has 500 nits, while my external ones only have 300 and 350. 

So, a locking solution needs to consider this, and yes, it will be absolutely worth the pain to do so. This is an excellent feature.

I would also gladly have the same locking solution for the volume. The same caveats apply to the volume level.

**Comment by cseelus** [comment]
Hi, @retrography , thanks for getting back

1. To get the grading to match will be very difficult I think, I don't know if this will be doable and necessary
2. Brightness Menulet has settings for the min-max values, which work quite well, at least for my setup (MBP 13" 2017 & Dell U2715H
![screen shot 2018-06-18 at 14 02 04](https://user-images.githubusercontent.com/3188392/41534817-3612e4d4-7300-11e8-9d1e-2ff0948e0d84.png)
3. See 2.

I can't say much about the volume settings though, as I only use Headphones (via TB3-Dock) or a pair of Speakers via Bluetooth.

**Comment by yedlosh** [comment]
Well I had tried the Brightness Menulet because of this, and it's Follow Main Screen option works great for me, but it has a bug that only one of my two identical monitors gets controlled, and it's apparently not supported anymore. So yeah.. It's a shame there still isn't one DDC app which has everything working.

**Comment by JoniVR** [comment]
I'm working on this in #148, I'm going to try to make it respect the "Change brightness/volume for all displays" checkbox and allow the user to select it from the display preferences. 

Not 100% sure how well it would work since talking to the internal display requires the usage of another (private) api, the same one other brightness tools use. Tracking progress mostly in there.
