### ISSUE TITLE
Ctrl + F1/F2 should change the internal monitor's brightness

### ISSUE THREAD

**Issue by tjarksaul** [the0neyouseek/MonitorControl#148]
This is the default behaviour on Apple monitors.

**Comment by jhildenbiddle** [comment]
I'd also like some way to control brightness of the internal display when using MonitorControl with an external monitor.

**Comment by yedlosh** [comment]
Right now I am using this one instead of MonitorControl to achieve that: 
https://github.com/Bensge/NativeDisplayBrightness

It has no UI, it's not supported anymore, but it simply controls brightness of all my external monitors at once using F1/F2. Which is actually everything I needed.

So Fn keys remain free to control internal display, and F1/F2 (for me actually Fn+F1/F2) control the external ones.. and it just works 👍

**Comment by JoniVR** [comment]
This is something that I plan on adding together with #118 but it requires a lot of rewriting under the hood.. and I'm very limited in time. I made some of the first steps in previous commit linked here (46d7cb6) rewriting the display managing logic.

**Comment by JoniVR** [comment]
Most of the code refactor is done, the internal display respects the `isEnabled` option inside settings and should also work with ctrl modifier (in that case no other displays will be controlled).

Just waiting for https://github.com/the0neyouseek/MediaKeyTap/pull/5 to be reviewed/merged right now. After that I'll do a few more final things and open a PR for review.

**Comment by the0neyouseek** [comment]
@JoniVR Merged :wink:
Thanks for all your hard work on this

**Comment by JoniVR** [comment]
Pull Request has been submitted! 

For the people that know how to, please feel free to test/review it and report any issues since a lot of the display logic has changed, there's always a bigger chance of introducing new issues. It's pretty hard to test with only one configuration so the more people that test it the better.
