### ISSUE TITLE
Issue detecting the output device

### ISSUE THREAD

**Issue by remus-b** [the0neyouseek/MonitorControl#172]
It would be very useful to detect the selected output. I'm not sure if this is possible but I find myself switching between the Monitor speakers and headphones.
The issue is that when I'm using the headphones the key for volume affects the volume of the monitor and not of the headphones. 
So I'm quitting the app each time I'm having this, which is many times a week.

**Comment by JoniVR** [comment]
![image](https://user-images.githubusercontent.com/7591717/73060914-334faf00-3e99-11ea-9523-32efb4577173.png)

Hi, this is already current behaviour. The app detects if the selected output device supports volume control. It also responds to changes in default audio device.

Perhaps your specific device reports back wrongly that it can't set it's own volume? 

Can you download the project, run it in xcode (after following the [how to build](https://github.com/the0neyouseek/MonitorControl#how-to-build) instructions) and then report your console output after switching volume? It should show something like this: 

![image](https://user-images.githubusercontent.com/7591717/73061261-0d76da00-3e9a-11ea-86c6-4187d6ace6bb.png)

**Comment by remus-b** [comment]
Thank you for your fast reply! 👍 
Going to test this out and let you know. 
My use-case is that I change from the menubar from the top right corner the output source. I also tried now at the hardware level (plug-out and in the headphone jack) but no change. 
Installing now the Xcode

**Comment by remus-b** [comment]
I can't manage to make a new build. Deleted the app. 
Any tips on how to do a clean install? maybe I have better chances.
My specs: Macbook Pro 15 2018
Monitor: LG 34UC99-W

Thank you.

**Comment by JoniVR** [comment]
What issue are you specifically running into?

**Comment by JoniVR** [comment]
One thing to keep in mind (for any other people running into this) is that MonitorControl uses the default output device. So you need to actually select the device you want to play sound from in de sound settings. 

![image](https://user-images.githubusercontent.com/7591717/74586982-88d93080-4fed-11ea-988d-6e3c0894c010.png)

**Comment by kevinjohncutler** [comment]
Turns out that "Listen for volume only" caused this bug for me. Changing it back to "listen for both" fixed it. Hopefully that gives a better idea of what causes the bug!

(I had the "volume only" toggle because I was using ExternalDisplayBrightness for brightness control, as they fixed the two-monitor-sync problem a while back).

**Comment by remus-b** [comment]
Yes, I was using it on "Listen for volume only" also. Because I don't need the brightness adjustments. Maybe this is something that is causing the bug. Let's hope for the best.
Thank you!

**Comment by JoniVR** [comment]
As you probably noticed a Pull Request has been submitted to fix this issue, thanks for identifying the issue in here, it helped solve it quicker 🙂

**Comment by kumowoon1025** [comment]
So I thought I successfully added the option to use SwiftPM instead of Carthage in my fork, but apparently I forgot to stage the actual swiftpm files so I'm trying to remember what I did months ago.

Then earlier I notice this stub of a branch that didn't look like any flow branch or anything, just one commit and not merged/finished, but apparently I have a ref to it somewhere, because it had me scratching my head for hours wondering why git wouldn't prune this for the love of

It was on my fork, of course. I thought I was starting to lose it. Why would something like that happen?? Did I pull after the commit on the "fix" branch and then some history-changing done on the upstream repo? I realize I can just zap the branch, it was merged but confused as to why my fork wouldnt reflect that 😕
