### ISSUE TITLE
Do I have the right version?

### ISSUE THREAD

**Issue by aeon3** [the0neyouseek/MonitorControl#56]
Hey,

I just downloaded what it seems to be v1.3.0 but the icon at the menu bar is different from the screenshot in the master branch. I also cannot see those complex keyboard shortcuts next to the "brightness" slider.

Can anyone enlighten me as to what could be going on?

**Comment by the0neyouseek** [comment]
Hi @aeon3 & @MHX792 

Yes you do have the right version, the screenshot on the readme is out of date. You can't see the keyboard shortcut next to the sliders because they doesn't exist anymore.

In this version you can control brightness/volume (⚠️ if your monitor is compatible) with your native mac keyboard keys or function keys.
