### ISSUE TITLE
Does not support HP Z24nf

### ISSUE THREAD

**Issue by benjaminburkhardt** [the0neyouseek/MonitorControl#68]
I'm currently using the old BrightnessMenulet  (https://github.com/superduper/BrightnessMenulet) which perfectly supports both of my screens in parallel. *HP Z24nf* and *Samsung U24E590*

This tool does only work with my Samsung monitor and does not show up the HP screen...

**Comment by reitermarkus** [comment]
Theoretically any display with DDC will work. If it doesn't, you'll have to dig into the code yourself since it's impossible for someone else to figure out without having the same monitor.

This may be related to https://github.com/the0neyouseek/MonitorControl/issues/71 though, so maybe fixing the other issue will make your monitor show up too.

**Comment by reitermarkus** [comment]
Have you tried if it shows up with version 1.4.0?
